# roundtripini/Taskfile (see https://taskfile.dev)

version: '3'

tasks:

  precommit:
    desc: Build and test
    cmds:
      - task: test

  clean:
    desc: Delete build artifacts
    cmds: [rm -rf bin/*]

  test:
    desc: Run all the tests
    cmds:
      - go test -coverprofile=cover.out ./...

  browser:
    desc: "show code coverage in browser (usage: task test browser)"
    cmds:
      - go tool cover -html=cover.out

